#name: Deploy to AWS S3
#on: [push]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Configure AWS Credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: us-west-2
#    - name: Install requirements
#    - run: |
#        python3 -m venv venv
#        source venv/bin/activate
#        pip install -r requirements.txt
#    - name: Make site static
#    - run: docnado --html public
#    - name: Deploy static site to S3 bucket
#      run: aws s3 sync ./public/ s3://<your-website-bucket> --delete
